# Generated by Django 5.2.5 on 2025-09-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
